### ISSUE TITLE
CORS header

### ISSUE THREAD

**Issue by guidovizoso** [benborgers/emojicdn#14]
Hi there! The CDN is awesome, congrats! 🥳 

I have this particular use case where I'm trying to retrieve the color palette from the emojis (any image actually but I just happen to be using your CDN) and to do that I have to add it to an HTML `canvas` element.
Since the image comes from a different origin than the website and no CORS header is preset the canvas gets _tainted_ and refuses to use methods like `getImageData()`. [The problem in detail](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#security_and_tainted_canvases)

I'm no PHP expert (I don't know anything about PHP actually) but I think that adding the CORS definition should do the trick.

`app/Http/Controllers/EmojiController.php` line 95
```php
return response($emojiImage)
            ->header('content-type', 'image/png');
            // ->header('Access-Control-Allow-Origin', '*'); or something like that
```

Please let me know if this is feasible and if you're willing to do that.

Have a great week!

**Comment by benborgers** [comment]
This is a good point! I think I've fixed it in 3120bf928d1e2af34dca2b8a4f4f9085f4790fe7, redeployed, and purged the cache. 

Let me know whether it works now!

**Comment by guidovizoso** [comment]
Works like a charm! Thanks a lot!

**Comment by benborgers** [comment]
Great!
