### ISSUE TITLE
zwj emoji 404

### ISSUE THREAD

**Issue by doveppp** [benborgers/emojicdn#43]
zwj emoji such as [here](https://emojipedia.org/emoji-zwj-sequence/) get response 404

**Comment by benborgers** [comment]
Hi! Could you provide an example of one that doesn’t work? Just spot-checking, they seem to work — for example [emojicdn.elk.sh/❤️‍🔥](https://emojicdn.elk.sh/❤️‍🔥)

**Comment by doveppp** [comment]
👩‍🤝‍👨
https://emojicdn.elk.sh/%F0%9F%91%A9%E2%80%8D%F0%9F%A4%9D%E2%80%8D%F0%9F%91%A8
