### ISSUE TITLE
Missing Microsoft Emoji

### ISSUE THREAD

**Issue by shawn-mcgee** [benborgers/emojicdn#45]
Hello, I use emojicdn to embed emoji into google sheets since they are not supported when exporting to PDF. I typically use the microsoft style for emojis and recently all of the emojis in my workbook disappeared because it appears that the microsoft style is no longer available.

**Comment by benborgers** [comment]
Hi! Unfortunately the Microsoft style isn't supported anymore, but you should be able to switch to one of the [supported styles](https://github.com/benborgers/emojicdn/blob/main/README.md) and it will work again.
