### ISSUE TITLE
Emoji CDN stopped working

### ISSUE THREAD

**Issue by sawyerpollard** [benborgers/emojicdn#47]
Hi Ben! Thanks for your cool CDN. I used it to build a website called https://whatsmuse.com
It was working but it looks like after a recent update it stopped working. You can see errors in the web console.
Just thought I'd let you know.

Also, I have a friend at Tufts who knows of you!

**Comment by benborgers** [comment]
Hi Sawyer! Thanks for pointing this out - this should be fixed now!

**Comment by sawyerpollard** [comment]
Awesome! Thank you.
