### ISSUE TITLE
jsDelivr was banned in China, can we maybe just return the image instead of `redirect`?

### ISSUE THREAD

**Issue by jw-12138** [benborgers/emojicdn#48]
hey ben,

i've noticed like 2 months ago, you changed the tech stack in this repo from php to cloudflare workers, also added redirect for emojis to further increase the cost-effectiveness(i think). but there is a problem now: the domain cdn.jsdelivr.com got banned in China like 2 years ago. as a result, this CDN won't be working in raw Chinese network environments.

i forked your repo and made my own deployment (emoji.jw1.dev), changing `redirect()` to `fetch()` seems to be working. so i'd like to propose you make the same change for better versatility, the only problem now is, what kinda impact will it have on the workers' performance and cost?

changes i made:  
https://github.com/jw-12138/emojicdn/blob/main/index.js#L33C1-L40C3

btw awesome project!

**Comment by benborgers** [comment]
Interesting, thanks for bringing this up! I've made that change to the code, and it should now return the image instead of redirecting. Does it seem to be working for you?

**Comment by jw-12138** [comment]
works great, thx man!
