### ISSUE TITLE
messenger style not working

### ISSUE THREAD

**Issue by dragonwocky** [benborgers/emojicdn#5]
I've tested a whole bunch of emojis with it and none of them seem to be working: I checked a url on emojipedia for a messenger-style emoji and it seems to have been also categorised under facebook in their file structure? https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/facebook/65/heavy-check-mark_2714.png

**Comment by benborgers** [comment]
Hmm yeah so it looks like the issue is that Emojipedia doesn't have “messenger” in the URL. You can do `?style=facebook`, though. I don't see an obvious way of distinguishing between facebook and messenger image files... it might be easier to just remove messenger as an option. Do you have a specific usecase for using messenger instead of facebook?

**Comment by dragonwocky** [comment]
Not specifically - one of my projects allows users to switch between emoji styles within the app, so I had been using this to make that easy and noticed that it was broken while testing. Removing it as an option might be best for now.

**Comment by benborgers** [comment]
That's a great use-case! I've removed the option (03f3b9d0bdb6abd5071ebf5a2482090ec443eab5), shouldn't be too much of a loss. 

Thanks for letting me know that it was broken!

**Comment by aprikyan** [comment]
Guys, removing Messenger set is not a solution! Facebook-style emojis on Emojipedia are stored in
`https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/[size]/facebook/230/[emoji_name].png`
while Messenger-style ones are in
`https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/[size]/facebook/65/[emoji_name].png`

Could you just add an
`if (style.toLowerCase()=="messenger") style="facebook/65"`
statement or something to solve the problem once and for all? I hope to see some cute Messenger-style emojis in my Notion :)
